# Generated by Django 2.2.27 on 2025-12-02 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251202_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentPermission',
        ),
    ]
