# Generated by Django 2.2.27 on 2025-12-02 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_delete_documentpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocumentAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('puede_descargar', models.BooleanField(default=True, verbose_name='Puede descargar')),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_acceso', to='core.DocumentFolder')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso a carpeta de usuario',
                'verbose_name_plural': 'Accesos a carpetas de usuario',
                'unique_together': {('usuario', 'carpeta')},
            },
        ),
    ]
