# Generated by Django 2.2.27 on 2025-12-02 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_rol_permiso_rolepermiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('AD', 'Administrador')], max_length=2, null=True, verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
